-- H2 2.1.212; 
;              
CREATE USER IF NOT EXISTS "SA" SALT 'cc20e234a304aa10' HASH '07f5d1d42b75cac70c6de4250a71a87d5197212b7fe3df1a55820e10c6ab5cf8' ADMIN;          
CREATE CACHED TABLE "PUBLIC"."flyway_schema_history"(
    "installed_rank" INTEGER NOT NULL,
    "version" CHARACTER VARYING(50),
    "description" CHARACTER VARYING(200) NOT NULL,
    "type" CHARACTER VARYING(20) NOT NULL,
    "script" CHARACTER VARYING(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" CHARACTER VARYING(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL
);           
ALTER TABLE "PUBLIC"."flyway_schema_history" ADD CONSTRAINT "PUBLIC"."flyway_schema_history_pk" PRIMARY KEY("installed_rank"); 
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.flyway_schema_history;    
INSERT INTO "PUBLIC"."flyway_schema_history" VALUES
(-1, NULL, '<< Flyway Schema History table created >>', 'TABLE', '', NULL, 'SA', TIMESTAMP '2023-04-04 02:07:31.397956', 0, TRUE),
(1, '1', 'create selectors table', 'SQL', 'V1__create_selectors_table.sql', 329259258, 'SA', TIMESTAMP '2023-04-04 02:07:31.447547', 31, TRUE);         
CREATE INDEX "PUBLIC"."flyway_schema_history_s_idx" ON "PUBLIC"."flyway_schema_history"("success" NULLS FIRST);
CREATE CACHED TABLE "PUBLIC"."USER_PREFERENCES_TBL"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "IS_TERM_ACCEPTED" BOOLEAN,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "UPDATED_AT" TIMESTAMP(6)
);       
ALTER TABLE "PUBLIC"."USER_PREFERENCES_TBL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");          
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.USER_PREFERENCES_TBL;     
INSERT INTO "PUBLIC"."USER_PREFERENCES_TBL" VALUES
(1, TIMESTAMP '2023-04-04 02:07:42.602', TRUE, 'Demo 5', TIMESTAMP '2023-04-04 02:07:42.602'),
(2, TIMESTAMP '2023-04-04 02:07:52.55', TRUE, 'Demo 6', TIMESTAMP '2023-04-04 02:08:03.525'),
(3, TIMESTAMP '2023-04-04 02:08:13.627', TRUE, 'Demo 1', TIMESTAMP '2023-04-04 02:08:13.627'),
(4, TIMESTAMP '2023-04-04 02:08:21.809', TRUE, 'User 3', TIMESTAMP '2023-04-04 02:08:21.809'),
(5, TIMESTAMP '2023-04-04 02:08:30.059', TRUE, 'User 5', TIMESTAMP '2023-04-04 02:08:30.059');         
CREATE CACHED TABLE "PUBLIC"."USER_SELECTOR"(
    "USER_PREFERENCE_ID" BIGINT NOT NULL,
    "SELECTOR_ID" BIGINT NOT NULL
);   
ALTER TABLE "PUBLIC"."USER_SELECTOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("USER_PREFERENCE_ID", "SELECTOR_ID");  
-- 7 +/- SELECT COUNT(*) FROM PUBLIC.USER_SELECTOR;            
INSERT INTO "PUBLIC"."USER_SELECTOR" VALUES
(1, 4),
(2, 69),
(2, 79),
(3, 78),
(4, 66),
(5, 14),
(5, 16);      
CREATE CACHED TABLE "PUBLIC"."SELECTORS_TBL"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 80) NOT NULL,
    "TITLE" CHARACTER VARYING(255) NOT NULL,
    "IS_PARENT" BOOLEAN DEFAULT 0 NOT NULL,
    "PARENT_SELECTOR_ID" INTEGER
);               
ALTER TABLE "PUBLIC"."SELECTORS_TBL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID"); 
-- 79 +/- SELECT COUNT(*) FROM PUBLIC.SELECTORS_TBL;           
INSERT INTO "PUBLIC"."SELECTORS_TBL" VALUES
(1, 'Manufacturing', TRUE, NULL, NULL),
(2, 'Other', TRUE, NULL, NULL),
(3, 'Service', TRUE, NULL, NULL),
(4, 'Construction materials', FALSE, 1, NULL),
(5, 'Electronics and Optics', FALSE, 1, NULL),
(6, 'Food and Beverage', FALSE, 1, NULL),
(7, 'Bakery confectionery products', FALSE, 6, NULL),
(8, 'Beverages', FALSE, 6, NULL),
(9, 'Fish fish products', FALSE, 6, NULL),
(10, 'Meat meat products', FALSE, 6, NULL),
(11, 'Milk dairy products', FALSE, 6, NULL),
(12, 'Other', FALSE, 6, NULL),
(13, 'Sweets snack food', FALSE, 6, NULL),
(14, 'Furniture', FALSE, 1, NULL),
(15, 'Bathroom/sauna', FALSE, 14, NULL),
(16, 'Bedroom', FALSE, 14, NULL),
(17, U&'Children\2019s room', FALSE, 14, NULL),
(18, 'Kitchen', FALSE, 14, NULL),
(19, 'Living room', FALSE, 14, NULL),
(20, 'Office', FALSE, 14, NULL),
(21, 'Other (Furniture)', FALSE, 14, NULL),
(22, 'Outdoor', FALSE, 14, NULL),
(23, 'Project furniture', FALSE, 14, NULL),
(24, 'Machinery', FALSE, 1, NULL),
(25, 'Machinery components', FALSE, 24, NULL),
(26, 'Machinery equipment/tools', FALSE, 24, NULL),
(27, 'Manufacture of machinery', FALSE, 24, NULL),
(28, 'Maritime', FALSE, 24, NULL),
(29, 'Aluminium and steel workboats', FALSE, 28, NULL),
(30, 'Boat/Yacht building', FALSE, 28, NULL),
(31, 'Ship repair and conversion', FALSE, 28, NULL),
(32, 'Metal structures', FALSE, 24, NULL),
(33, 'Other', FALSE, 24, NULL),
(34, 'Repair and maintenance service', FALSE, 24, NULL),
(35, 'Metalworking', FALSE, 1, NULL),
(36, 'Construction of metal structures', FALSE, 35, NULL),
(37, 'Houses and buildings', FALSE, 35, NULL),
(38, 'Metal products', FALSE, 35, NULL),
(39, 'Metal works', FALSE, 35, NULL),
(40, 'CNC-machining', FALSE, 39, NULL),
(41, 'Forgings, Fasteners', FALSE, 39, NULL),
(42, 'Gas, Plasma, Laser cutting', FALSE, 39, NULL),
(43, 'MIG, TIG, Aluminum welding', FALSE, 39, NULL),
(44, 'Plastic and Rubber', FALSE, 1, NULL),
(45, 'Packaging', FALSE, 44, NULL),
(46, 'Plastic goods', FALSE, 44, NULL),
(47, 'Plastic processing technology', FALSE, 44, NULL),
(48, 'Blowing', FALSE, 47, NULL),
(49, 'Moulding', FALSE, 47, NULL),
(50, 'Plastics welding and processing', FALSE, 47, NULL),
(51, 'Plastic profiles', FALSE, 44, NULL),
(52, 'Printing', FALSE, 1, NULL),
(53, 'Labelling and packaging printing', FALSE, 52, NULL),
(54, 'Book/Periodicals printing', FALSE, 52, NULL),
(55, 'Advertising', FALSE, 52, NULL),
(56, 'Textile and Clothing', FALSE, 1, NULL),
(57, 'Clothing', FALSE, 56, NULL),
(58, 'Textile', FALSE, 56, NULL),
(59, 'Wood', FALSE, 1, NULL),
(60, 'Other (Wood)', FALSE, 59, NULL),
(61, 'Wooden building materials', FALSE, 59, NULL),
(62, 'Wooden houses', FALSE, 59, NULL),
(63, 'Creative industries', FALSE, 2, NULL),
(64, 'Energy technology', FALSE, 2, NULL),
(65, 'Environment', FALSE, 2, NULL),
(66, 'Business services', FALSE, 3, NULL),
(67, 'Engineering', FALSE, 3, NULL),
(68, 'Information Technology and Telecommunications', FALSE, 3, NULL),
(69, 'Data processing, Web portals, E-marketing', FALSE, 68, NULL),
(70, 'Programming, Consultancy', FALSE, 68, NULL),
(71, 'Software, Hardware', FALSE, 68, NULL),
(72, 'Telecommunications', FALSE, 68, NULL),
(73, 'Tourism', FALSE, 3, NULL),
(74, 'Translation services', FALSE, 3, NULL),
(75, 'Transport and Logistics', FALSE, 3, NULL),
(76, 'Air', FALSE, 75, NULL),
(77, 'Rail', FALSE, 75, NULL),
(78, 'Road', FALSE, 75, NULL),
(79, 'Water', FALSE, 75, NULL);           
ALTER TABLE "PUBLIC"."USER_SELECTOR" ADD CONSTRAINT "PUBLIC"."FKBVYO77RG2M75VQFJ7YYCTTV2O" FOREIGN KEY("USER_PREFERENCE_ID") REFERENCES "PUBLIC"."USER_PREFERENCES_TBL"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."SELECTORS_TBL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3A" FOREIGN KEY("PARENT_SELECTOR_ID") REFERENCES "PUBLIC"."SELECTORS_TBL"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."USER_SELECTOR" ADD CONSTRAINT "PUBLIC"."FKKWUXEQMCR2WGEOWLKUJBKGM0T" FOREIGN KEY("SELECTOR_ID") REFERENCES "PUBLIC"."SELECTORS_TBL"("ID") NOCHECK;
